site_name: Serapeum Documentation
site_description: Centralized documentation for Serapeum GitHub Organization
site_url: https://serapieum-of-alex.github.io/docs/
theme:
  name: material
  language: en
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference

nav:
  - Home: index.md
  - hydrological-modeling:
      - Repo 1: hydrological-modeling/digital-rivers.md
      - Repo 2: hydrological-modeling/hapi.md
  - Contributing: contributing.md
  - About: about.md

plugins:
  - search
  - autolinks
  - redirects
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: ["!^_"]
            heading_level: 1
            members_order: source
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/Serapieum-of-alex
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/mafarrag/
  - icon: fontawesome/brands/medium
    link: https://medium.com/hydroinformatics
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js